#将来的には対応する規約の読み込み
inherit_from: .rubocop_todo.yml

#追加した規約ファイル読み込み
require:
  - rubocop-rails

AllCops:
  #Rubyバージョン指定
  TargetRubyVersion: 2.5.7
  #除外
  Exclude:
    - 'config.ru'
    - 'bin/**'
    - 'lib/**'
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'
    - !ruby/regexp /old_and_unused\.rb$/

#日本語でのコメントを許可
AsciiComments:
  Enables: false

#クラスのコメント必須を無視
Style/Documentation:
  Enabled: false

#モジュール名::クラス名の定義を許可
Style/ClassAndModuleChildren:
  Enabled: false

#文字リテラルのイミュータブル宣言を無視
Style/FrozenStringLiteralComment:
  Enabled: false

# For rubocop < 1.0.0
Style/HashEachMethods:
  Enabled: true

# For rubocop < 1.0.0
Style/HashTransformKeys:
  Enabled: true

# For rubocop < 1.0.0
Style/HashTransformValues:
  Enabled: true
